# tb/cocotb/common/axi_ram.py

import cocotb
from cocotb.triggers import RisingEdge
from collections import deque
from dataclasses import dataclass


@dataclass
class WriteAddrTxn:
    addr: int
    length: int
    size: int
    burst: int


@dataclass
class WriteBeat:
    data: int
    strb: int
    last: bool


@dataclass
class ReadAddrTxn:
    addr: int
    length: int
    size: int
    burst: int


class AXI4RAM:
    """
    AXI4 RAM model for flash_attn_top.

    Key assumptions:
      - AXI data width = 64-bit
      - one AXI beat = 8 bytes
      - AXI burst type = INCR
      - Q/K/V/O data format = signed Q8.8 int16
      - gen_vectors.py hex format = one 16-bit element per line
      - memory is byte-addressable
      - little-endian packing:
            lower address -> lower bits
            element 0 -> bits [15:0]
            element 1 -> bits [31:16]
            element 2 -> bits [47:32]
            element 3 -> bits [63:48]
    """

    AXI_BYTES = 8
    AXI_RESP_OKAY = 0
    AXI_BURST_INCR = 1
    AXI_SIZE_64BIT = 3

    def __init__(self, dut, clk, rst_n):
        self.dut = dut
        self.clk = clk
        self.rst_n = rst_n

        # Byte-addressable memory:
        #   key   = byte address
        #   value = one byte, 0..255
        self.mem = {}

        # Decoupled AXI queues
        self._aw_queue = deque()
        self._w_queue = deque()
        self._ar_queue = deque()

        self._drive_all_idle()

        cocotb.start_soon(self._ar_channel())
        cocotb.start_soon(self._read_response_channel())
        cocotb.start_soon(self._aw_channel())
        cocotb.start_soon(self._w_channel())
        cocotb.start_soon(self._write_response_channel())

    # ------------------------------------------------------------------
    # Public memory helper APIs
    # ------------------------------------------------------------------

    def load_i16_array(self, base_addr, data_list):
        """
        Load a flat list of int16/Q8.8 values into memory.

        Mapping:
            data_list[i] -> byte address base_addr + i * 2
        """
        for i, val in enumerate(data_list):
            self._write_u16(base_addr + i * 2, int(val) & 0xFFFF)

    def load_hex_i16_file(self, base_addr, filename):
        """
        Load a .hex file generated by model/gen_vectors.py.

        File format:
            one 16-bit hex value per line, row-major order.

        Returns:
            number of int16 elements loaded.
        """
        count = 0
        with open(filename, "r") as f:
            for line in f:
                s = line.strip()
                if not s:
                    continue

                raw = int(s, 16) & 0xFFFF
                self._write_u16(base_addr + count * 2, raw)
                count += 1

        return count

    def dump_i16_array(self, base_addr, num_elems):
        """
        Dump memory as signed int16 list.

        Useful for reading O output from O_BASE.
        """
        out = []
        for i in range(num_elems):
            raw = self._read_u16(base_addr + i * 2)
            if raw & 0x8000:
                raw -= 0x10000
            out.append(raw)
        return out

    def dump_hex_i16_file(self, base_addr, num_elems, filename):
        """
        Dump memory to one-16-bit-hex-per-line format.
        """
        with open(filename, "w") as f:
            for i in range(num_elems):
                raw = self._read_u16(base_addr + i * 2)
                f.write(f"{raw & 0xFFFF:04X}\n")

    def load_u64_words(self, base_addr, data_list):
        """
        Load a list of 64-bit AXI words into memory.

        This is for low-level AXI tests only.
        Do not use this directly for input_q.hex/input_k.hex/input_v.hex,
        because those files are one int16 element per line.
        """
        for i, val in enumerate(data_list):
            self._write_u64(base_addr + i * self.AXI_BYTES, int(val), 0xFF)

    def load_data_array(self, base_addr, data_list):
        """
        Backward-compatible alias.

        Warning:
            This treats each item as one 64-bit AXI word.
            It does NOT match gen_vectors.py's one-int16-per-line hex format.
        """
        self.load_u64_words(base_addr, data_list)

    # ------------------------------------------------------------------
    # Low-level byte-addressable memory
    # ------------------------------------------------------------------

    def _write_byte(self, addr, val):
        self.mem[int(addr)] = int(val) & 0xFF

    def _read_byte(self, addr):
        return self.mem.get(int(addr), 0) & 0xFF

    def _write_u16(self, addr, val):
        val = int(val) & 0xFFFF
        self._write_byte(addr + 0, (val >> 0) & 0xFF)
        self._write_byte(addr + 1, (val >> 8) & 0xFF)

    def _read_u16(self, addr):
        b0 = self._read_byte(addr + 0)
        b1 = self._read_byte(addr + 1)
        return b0 | (b1 << 8)

    def _write_u64(self, addr, val, wstrb=0xFF):
        """
        Write one 64-bit AXI beat with byte strobe.
        """
        val = int(val) & ((1 << 64) - 1)
        wstrb = int(wstrb) & 0xFF

        for b in range(self.AXI_BYTES):
            if (wstrb >> b) & 1:
                self._write_byte(addr + b, (val >> (8 * b)) & 0xFF)

    def _read_u64(self, addr):
        """
        Read one 64-bit AXI beat.
        """
        val = 0
        for b in range(self.AXI_BYTES):
            val |= self._read_byte(addr + b) << (8 * b)
        return val & ((1 << 64) - 1)

    # ------------------------------------------------------------------
    # Signal helpers
    # ------------------------------------------------------------------

    def _drive_all_idle(self):
        self.dut.m_axi_arready.value = 0

        self.dut.m_axi_rvalid.value = 0
        self.dut.m_axi_rdata.value = 0
        self.dut.m_axi_rresp.value = 0
        self.dut.m_axi_rlast.value = 0

        self.dut.m_axi_awready.value = 0

        self.dut.m_axi_wready.value = 0

        self.dut.m_axi_bvalid.value = 0
        self.dut.m_axi_bresp.value = 0

    def _clear_queues(self):
        self._aw_queue.clear()
        self._w_queue.clear()
        self._ar_queue.clear()

    def _is_one(self, sig):
        """
        Safe signal == 1 check.
        X/Z values return False.
        """
        try:
            val = sig.value
            if hasattr(val, "is_resolvable") and not val.is_resolvable:
                return False
            return int(val) == 1
        except Exception:
            return False

    def _get_int(self, sig, name="signal"):
        """
        Convert signal to int and fail loudly on X/Z.
        """
        val = sig.value

        if hasattr(val, "is_resolvable") and not val.is_resolvable:
            raise AssertionError(f"{name} has X/Z value: {val}")

        return int(val)

    def _in_reset(self):
        try:
            val = self.rst_n.value
            if hasattr(val, "is_resolvable") and not val.is_resolvable:
                return True
            return int(val) == 0
        except Exception:
            return True

    def _check_axi_addr(self, addr, size, burst, channel_name):
        """
        Baseline AXI constraint check.
        """
        assert size == self.AXI_SIZE_64BIT, (
            f"{channel_name}: only 64-bit AXI beats are supported. "
            f"Expected SIZE=3, got SIZE={size}"
        )

        assert burst == self.AXI_BURST_INCR, (
            f"{channel_name}: only INCR burst is supported. "
            f"Expected BURST=1, got BURST={burst}"
        )

        assert addr % self.AXI_BYTES == 0, (
            f"{channel_name}: unaligned AXI address 0x{addr:X}. "
            f"Expected {self.AXI_BYTES}-byte alignment."
        )

    # ------------------------------------------------------------------
    # AXI read address channel: AR
    # ------------------------------------------------------------------

    async def _ar_channel(self):
        while True:
            # Drive ARREADY before the next clock edge.
            if self._in_reset():
                self.dut.m_axi_arready.value = 0
            else:
                self.dut.m_axi_arready.value = 1

            await RisingEdge(self.clk)

            if self._in_reset():
                self.dut.m_axi_arready.value = 0
                self._ar_queue.clear()
                continue

            if self._is_one(self.dut.m_axi_arvalid) and self._is_one(self.dut.m_axi_arready):
                addr = self._get_int(self.dut.m_axi_araddr, "m_axi_araddr")
                length = self._get_int(self.dut.m_axi_arlen, "m_axi_arlen") + 1
                size = self._get_int(self.dut.m_axi_arsize, "m_axi_arsize")
                burst = self._get_int(self.dut.m_axi_arburst, "m_axi_arburst")

                self._check_axi_addr(addr, size, burst, "AR")

                self._ar_queue.append(
                    ReadAddrTxn(
                        addr=addr,
                        length=length,
                        size=size,
                        burst=burst,
                    )
                )

    # ------------------------------------------------------------------
    # AXI read data channel: R
    # ------------------------------------------------------------------

    async def _read_response_channel(self):
        while True:
            await RisingEdge(self.clk)

            if self._in_reset():
                self.dut.m_axi_rvalid.value = 0
                self.dut.m_axi_rdata.value = 0
                self.dut.m_axi_rresp.value = 0
                self.dut.m_axi_rlast.value = 0
                self._ar_queue.clear()
                continue

            if not self._ar_queue:
                self.dut.m_axi_rvalid.value = 0
                self.dut.m_axi_rlast.value = 0
                continue

            txn = self._ar_queue.popleft()
            aborted = False

            for beat in range(txn.length):
                beat_addr = txn.addr + beat * self.AXI_BYTES

                self.dut.m_axi_rdata.value = self._read_u64(beat_addr)
                self.dut.m_axi_rresp.value = self.AXI_RESP_OKAY
                self.dut.m_axi_rlast.value = 1 if beat == txn.length - 1 else 0
                self.dut.m_axi_rvalid.value = 1

                while True:
                    await RisingEdge(self.clk)

                    if self._in_reset():
                        self.dut.m_axi_rvalid.value = 0
                        self.dut.m_axi_rdata.value = 0
                        self.dut.m_axi_rresp.value = 0
                        self.dut.m_axi_rlast.value = 0
                        self._ar_queue.clear()
                        aborted = True
                        break

                    if self._is_one(self.dut.m_axi_rready):
                        break

                if aborted:
                    break

            self.dut.m_axi_rvalid.value = 0
            self.dut.m_axi_rdata.value = 0
            self.dut.m_axi_rresp.value = 0
            self.dut.m_axi_rlast.value = 0

    # ------------------------------------------------------------------
    # AXI write address channel: AW
    # ------------------------------------------------------------------

    async def _aw_channel(self):
        while True:
            # Drive AWREADY before the next clock edge.
            if self._in_reset():
                self.dut.m_axi_awready.value = 0
            else:
                self.dut.m_axi_awready.value = 1

            await RisingEdge(self.clk)

            if self._in_reset():
                self.dut.m_axi_awready.value = 0
                self._aw_queue.clear()
                continue

            if self._is_one(self.dut.m_axi_awvalid) and self._is_one(self.dut.m_axi_awready):
                addr = self._get_int(self.dut.m_axi_awaddr, "m_axi_awaddr")
                length = self._get_int(self.dut.m_axi_awlen, "m_axi_awlen") + 1
                size = self._get_int(self.dut.m_axi_awsize, "m_axi_awsize")
                burst = self._get_int(self.dut.m_axi_awburst, "m_axi_awburst")

                self._check_axi_addr(addr, size, burst, "AW")

                self._aw_queue.append(
                    WriteAddrTxn(
                        addr=addr,
                        length=length,
                        size=size,
                        burst=burst,
                    )
                )

    # ------------------------------------------------------------------
    # AXI write data channel: W
    # ------------------------------------------------------------------

    async def _w_channel(self):
        while True:
            # Drive WREADY before the next clock edge.
            # This allows W to arrive before AW.
            if self._in_reset():
                self.dut.m_axi_wready.value = 0
            else:
                self.dut.m_axi_wready.value = 1

            await RisingEdge(self.clk)

            if self._in_reset():
                self.dut.m_axi_wready.value = 0
                self._w_queue.clear()
                continue

            if self._is_one(self.dut.m_axi_wvalid) and self._is_one(self.dut.m_axi_wready):
                data = self._get_int(self.dut.m_axi_wdata, "m_axi_wdata")
                strb = self._get_int(self.dut.m_axi_wstrb, "m_axi_wstrb")
                last = self._is_one(self.dut.m_axi_wlast)

                self._w_queue.append(
                    WriteBeat(
                        data=data,
                        strb=strb,
                        last=last,
                    )
                )

    # ------------------------------------------------------------------
    # AXI write response channel: B
    # ------------------------------------------------------------------

    async def _write_response_channel(self):
        while True:
            await RisingEdge(self.clk)

            if self._in_reset():
                self.dut.m_axi_bvalid.value = 0
                self.dut.m_axi_bresp.value = self.AXI_RESP_OKAY
                self._aw_queue.clear()
                self._w_queue.clear()
                continue

            if not self._aw_queue:
                self.dut.m_axi_bvalid.value = 0
                continue

            aw = self._aw_queue.popleft()
            beats = []
            aborted = False

            # Collect W beats for this AW burst.
            # Since AXI4 has no WID, write data ordering follows AW ordering.
            while len(beats) < aw.length:
                if self._in_reset():
                    self.dut.m_axi_bvalid.value = 0
                    self.dut.m_axi_bresp.value = self.AXI_RESP_OKAY
                    self._aw_queue.clear()
                    self._w_queue.clear()
                    aborted = True
                    break

                if self._w_queue:
                    beats.append(self._w_queue.popleft())
                else:
                    await RisingEdge(self.clk)

            if aborted:
                continue

            # Check WLAST placement and write memory.
            for beat_idx, beat in enumerate(beats):
                expected_last = beat_idx == aw.length - 1

                assert beat.last == expected_last, (
                    f"AXI WLAST error at beat {beat_idx}. "
                    f"Expected last={expected_last}, got last={beat.last}. "
                    f"AW addr=0x{aw.addr:X}, burst_len={aw.length}"
                )

                beat_addr = aw.addr + beat_idx * self.AXI_BYTES
                self._write_u64(beat_addr, beat.data, beat.strb)

            # Send B response.
            self.dut.m_axi_bresp.value = self.AXI_RESP_OKAY
            self.dut.m_axi_bvalid.value = 1

            while True:
                await RisingEdge(self.clk)

                if self._in_reset():
                    self.dut.m_axi_bvalid.value = 0
                    self.dut.m_axi_bresp.value = self.AXI_RESP_OKAY
                    self._aw_queue.clear()
                    self._w_queue.clear()
                    aborted = True
                    break

                if self._is_one(self.dut.m_axi_bready):
                    break

            self.dut.m_axi_bvalid.value = 0
            self.dut.m_axi_bresp.value = self.AXI_RESP_OKAY
